### ISSUE TITLE
Making use of the `fortigate-api` Python package.

### ISSUE THREAD

**Issue by rickmoonex** [joshbergm/Python-Networking#14]
Hey Joshua, repo ziet er goed uit ;)

Heb een tip die je misschien kunt toepassen. Ik heb thuis de FortiGate geautomatiseerd met het `fortigate-api` Python package. Zie [hier](https://pypi.org/project/fortigate-api/).

Maakt gebruik van de REST API i.p.v. SSH. Misschien niet zo makkelijk in gebruik, maar zorgt er wel voor dat je commando's in parallel kunt uitvoeren. En aangezien de REST API werkt met JSON is deze data makkelijk te parsen en/of manipuleren met Python functies.

Keep up the good work!

**Comment by rickmoonex** [comment]
Mijn implementatie:

```python
import os

from fortigate_api import FortiGateAPI

HOST = os.getenv("FORTIGATE_HOST")
TOKEN = os.getenv("FORTIGATE_TOKEN")

api = FortiGateAPI(host=HOST, token=TOKEN)

data = {
    "name": "ADDRESS",
    "obj-type": "ip",
    "subnet": "127.0.0.100 255.255.255.252",
    "type": "ipmask",
}
response = api.cmdb.firewall.address.create(data)
print(f"address.create {response}")
```

Hij haalt hier de host en token op uit de environment variables FORTIGATE_HOST en FORTIGATE_TOKEN.

**Comment by joshbergm** [comment]
Thx! :)
